In [ ]:
import pandas as pd
import numpy as np


import matplotlib.pyplot as plt
import seaborn as sns


from ydata_profiling import ProfileReport

In [ ]:

df = pd.read_csv("C:/Users/layel/Downloads/Electric_cars_dataset.csv")


df.head()

,ID,VIN (1-10),County,City,State,ZIP Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,Expected Price ($1k)
0,EV33174,5YJ3E1EC6L,Snohomish,LYNNWOOD,WA,98037.0,2020.0,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,308,0,32.0,109821694,POINT (-122.287614 47.83874),PUGET SOUND ENERGY INC,50
1,EV40247,JN1AZ0CP8B,Skagit,BELLINGHAM,WA,98229.0,2011.0,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,73,0,40.0,137375528,POINT (-122.414936 48.709388),PUGET SOUND ENERGY INC,15
2,EV12248,WBY1Z2C56F,Pierce,TACOMA,WA,98422.0,2015.0,BMW,I3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,81,0,27.0,150627382,POINT (-122.396286 47.293138),BONNEVILLE POWER ADMINISTRATION||CITY OF TACOM...,18
3,EV55713,1G1RD6E44D,King,REDMOND,WA,98053.0,2013.0,CHEVROLET,VOLT,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,38,0,45.0,258766301,POINT (-122.024951 47.670286),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),33.9
4,EV28799,1G1FY6S05K,Pierce,PUYALLUP,WA,98375.0,2019.0,CHEVROLET,BOLT EV,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,238,0,25.0,296998138,POINT (-122.321062 47.103797),BONNEVILLE POWER ADMINISTRATION||CITY OF TACOM...,41.78

In [3]:
df.shape

(64353, 18)

In [4]:
df.columns

Index(['ID', 'VIN (1-10)', 'County', 'City', 'State', 'ZIP Code', 'Model Year',
       'Make', 'Model', 'Electric Vehicle Type',
       'Clean Alternative Fuel Vehicle (CAFV) Eligibility', 'Electric Range',
       'Base MSRP', 'Legislative District', 'DOL Vehicle ID',
       'Vehicle Location', 'Electric Utility', 'Expected Price ($1k)'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64353 entries, 0 to 64352
Data columns (total 18 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   ID                                                 64353 non-null  object
 1   VIN (1-10)                                         64353 non-null  object
 2   County                                             64349 non-null  object
 3   City                                               64344 non-null  object
 4   State                                              64342 non-null  object
 5   ZIP Code                                           64347 non-null  float64
 6   Model Year                                         64346 non-null  float64
 7   Make                                               64349 non-null  object
 8   Model                                              64340 non-null  object
 9   Electric Vehicle Type                              64353 non-null  object
 10  Clean Alternative Fuel Vehicle (CAFV) Eligibility  64353 non-null  object
 11  Electric Range                                     64353 non-null  int64
 12  Base MSRP                                          64353 non-null  int64
 13  Legislative District                               64184 non-null  float64
 14  DOL Vehicle ID                                     64353 non-null  int64
 15  Vehicle Location                                   63843 non-null  object
 16  Electric Utility                                   63631 non-null  object
 17  Expected Price ($1k)                               64353 non-null  object
dtypes: float64(3), int64(3), object(12)
memory usage: 8.8+ MB

In [6]:
df.describe()

,ZIP Code,Model Year,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID
count,64347.000000,64346.000000,64353.000000,64353.000000,64184.000000,6.435300e+04
mean,98143.452888,2018.186212,106.948985,2524.990754,29.951904,1.972905e+08
std,2856.064329,2.726742,104.093919,12402.895104,14.661124,1.069466e+08
min,745.000000,1993.000000,0.000000,0.000000,0.000000,4.385000e+03
25%,98052.000000,2017.000000,14.000000,0.000000,19.000000,1.372865e+08
50%,98121.000000,2018.000000,73.000000,0.000000,34.000000,1.753776e+08
75%,98370.000000,2021.000000,215.000000,0.000000,43.000000,2.299039e+08
max,99701.000000,2022.000000,337.000000,845000.000000,49.000000,4.789346e+08

In [7]:
df.isnull().sum()

ID                                                     0
VIN (1-10)                                             0
County                                                 4
City                                                   9
State                                                 11
ZIP Code                                               6
Model Year                                             7
Make                                                   4
Model                                                 13
Electric Vehicle Type                                  0
Clean Alternative Fuel Vehicle (CAFV) Eligibility      0
Electric Range                                         0
Base MSRP                                              0
Legislative District                                 169
DOL Vehicle ID                                         0
Vehicle Location                                     510
Electric Utility                                     722
Expected Price ($1k)                                   0
dtype: int64

In [8]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])
print("Duplicate rows:", df.duplicated().sum())

Number of rows: 64353
Number of columns: 18
Duplicate rows: 0

In [ ]:
import pandas as pd
from ydata_profiling import ProfileReport

df = pd.read_csv("C:/Users/layel/Downloads/Electric_cars_dataset.csv")  # adjust path if needed


print(df.shape)
df.head()


profile = ProfileReport(df, title="Electric Vehicle Data Profiling Report", explorative=True)

profile.to_file("EV_Data_Report.html")
print("Profile report saved as EV_Data_Report.html")

(64353, 18)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 18/18 [00:04<00:00,  4.41it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

Profile report saved as EV_Data_Report.html

In [10]:
df.isnull().sum()

ID                                                     0
VIN (1-10)                                             0
County                                                 4
City                                                   9
State                                                 11
ZIP Code                                               6
Model Year                                             7
Make                                                   4
Model                                                 13
Electric Vehicle Type                                  0
Clean Alternative Fuel Vehicle (CAFV) Eligibility      0
Electric Range                                         0
Base MSRP                                              0
Legislative District                                 169
DOL Vehicle ID                                         0
Vehicle Location                                     510
Electric Utility                                     722
Expected Price ($1k)                                   0
dtype: int64

In [8]:
num_cols = df.select_dtypes(include=np.number).columns
cat_cols = df.select_dtypes(include='object').columns

In [ ]:

for col in num_cols:
    df[col].fillna(df[col].median(), inplace=True)


for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

C:\Users\layel\AppData\Local\Temp\ipykernel_6328\2278322238.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\layel\AppData\Local\Temp\ipykernel_6328\2278322238.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\layel\AppData\Local\Temp\ipykernel_6328\2278322238.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\layel\AppData\Local\Temp\ipykernel_6328\2278322238.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\layel\AppData\Local\Temp\ipykernel_6328\2278322238.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\layel\AppData\Local\Temp\ipykernel_6328\2278322238.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\layel\AppData\Local\Temp\ipykernel_6328\2278322238.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [10]:
df = df.drop_duplicates()

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
plt.figure(figsize=(8, 4))
sns.boxplot(x=df["Base MSRP"])
plt.show()

C:\Users\layel\AppData\Local\Temp\ipykernel_6328\1631390469.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [13]:
Q1 = df["Base MSRP"].quantile(0.25)
Q3 = df["Base MSRP"].quantile(0.75)
IQR = Q3 - Q1

df = df[
    (df["Base MSRP"] >= Q1 - 1.5 * IQR) &
    (df["Base MSRP"] <= Q3 + 1.5 * IQR)
]

In [14]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in cat_cols:
    df[col] = le.fit_transform(df[col])

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 61263 entries, 0 to 64352
Data columns (total 18 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   ID                                                 61263 non-null  int64
 1   VIN (1-10)                                         61263 non-null  int64
 2   County                                             61263 non-null  int64
 3   City                                               61263 non-null  int64
 4   State                                              61263 non-null  int64
 5   ZIP Code                                           61263 non-null  float64
 6   Model Year                                         61263 non-null  float64
 7   Make                                               61263 non-null  int64
 8   Model                                              61263 non-null  int64
 9   Electric Vehicle Type                              61263 non-null  int64
 10  Clean Alternative Fuel Vehicle (CAFV) Eligibility  61263 non-null  int64
 11  Electric Range                                     61263 non-null  int64
 12  Base MSRP                                          61263 non-null  int64
 13  Legislative District                               61263 non-null  float64
 14  DOL Vehicle ID                                     61263 non-null  int64
 15  Vehicle Location                                   61263 non-null  int64
 16  Electric Utility                                   61263 non-null  int64
 17  Expected Price ($1k)                               61263 non-null  int64
dtypes: float64(3), int64(15)
memory usage: 8.9 MB

In [16]:
df.head()

,ID,VIN (1-10),County,City,State,ZIP Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,Expected Price ($1k)
0,17176,1888,117,265,35,98037.0,2020.0,26,50,0,0,308,0,32.0,109821694,313,65,140
1,22355,2848,115,38,35,98229.0,2011.0,21,47,0,0,73,0,40.0,137375528,375,65,26
2,1673,4205,93,465,35,98422.0,2015.0,3,40,0,0,81,0,27.0,150627382,367,20,36
3,33900,636,60,385,35,98053.0,2013.0,5,83,1,0,38,0,45.0,258766301,240,66,105
4,13958,318,93,374,35,98375.0,2019.0,5,12,0,0,238,0,25.0,296998138,333,16,125

In [ ]:

target = "Base MSRP"  
X = df.drop(columns=[target])  
y = df[target]

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training set:", X_train.shape)
print("Test set:", X_test.shape)

Training set: (49010, 17)
Test set: (12253, 17)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
from sklearn.svm import SVR

svm_model = SVR(kernel='rbf')

svm_model.fit(X_train_scaled, y_train)

SVR()

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np


y_pred = svm_model.predict(X_test_scaled)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R² score: {r2:.2f}")

MAE: 0.00
RMSE: 0.00
R² score: 1.00